### ISSUE TITLE
无法通过参数指定只构建新的包

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#46]
比如我添加了一个新的包a到repo, 然后lilac a
会报错unknown packages: {'a'}
其实是因为 No such file or directory: repodir+'/a'
理论上说只要先git pull就好了...

**Comment by lilydjwg** [comment]
那你 git pull 一下就好了嘛。指定包名本来就是手动构建指定包的，所以手动准备好工作区。

2017年10月3日 15:03，"Jingbei Li" <notifications@github.com>写道：

比如我添加了一个新的包a到repo, 然后lilac a
会报错unknown packages: {'a'}
其实是因为 No such file or directory: repodir+'a'
理论上说只要先git pull就好了...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/archlinuxcn/lilac/issues/46>, or mute the thread

**Comment by petronny** [comment]
呃也有道理
